### ISSUE TITLE
Add second based timer

### ISSUE THREAD

**Issue by devenini** [CreativeTechGuy/tree-despawn-timer#5]
Hey, great plugin!

Would be nice to also have the possibility to display a second based timer, in the same dropdown of "Pie" and "Ticks". Similar to how other timers work.

**Comment by CreativeTechGuy** [comment]
Hey thanks! I considered doing this, but I felt that having seconds implies a level of precision which isn't there. That's also why "pie" is the default despite that I don't think it looks the best. You might have noticed that sometimes trees are cut down when there's still 20+ ticks left, sometimes they stay standing for a log or two after it hits zero. I have no clue why it isn't precise and I'm not sure there's enough information from the client to know that definitively since it's based on actions of other players.

So I felt that not showing an exact time would be better so people didn't get upset when the time proved to be inaccurate (which it will).

**Comment by CreativeTechGuy** [comment]
I think I've come around to this. I'll be adding a time setting to the timer display in the next release.
